name: "cd workflow"

on:
    workflow_run:
        workflows: ["React CI/CD workflows"]
        types: 
            - completed
        
    workflow_dispatch:
  
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: "set-up nodejs"
              uses:  actions/setup-node@v4