name: "React CI/CD workflows" 

on: 
    push:
        branches:
           - push
           - master
           - main

jobs:
    react-ci-workflow :
                    runs-on: ubntu-latest

    steps:
        - name: "set-up nodejs"
             uses:  actions/setup-node@V4
             with: 
              node-versions:'21'
        
        - name: "check node version"
          run : node --version