name: "React CI/CD workflows" 

on: 
    push:
        branches:
           
           - master
           - main

jobs:
    react-ci-workflow:
                runs-on: ubuntu-latest
                steps:
                     - name: "set-up nodejs"
                       uses:  actions/setup-node@v4
                       with: 
                           node-version: 21

        
                     - name: "check node version"
                       run: node --version

                     - name: "List of dict"
                       run: ls

                     - name: "Clone the repository"
                       uses: actions/checkout@v4

                     - name: "Install dependencies"
                       run: npm install

                     - name: "List of dict"
                       run: ls
                    
                     - name: "Run build"
                       run: npm run build