name: "React CI/CD workflows" 

on: 
    push:
        branches:
           
           - master
           - main

jobs:
    react-ci-workflow:
                runs-on: ubuntu-latest


    steps:
        - name: "set-up nodejs"
            uses:  actions/setup-node@V4
            with: 
                 node-versions:'21'

        
        - name: "check node version"
          run : node --version